### ISSUE TITLE
Doctrine dependency not mentioned in docs

### ISSUE THREAD

**Issue by dwalker109** [RobinMalfait/Laravel-auto-form-generator#12]
Hi, just thought I would mention that since Doctrine is no longer installed in Laravel by default, Doctine needs to be pulled in before this (rather fabulous) package works. I couldn't see any mention of this in the docs or composer install.

Thanks!

**Comment by Jimbolino** [comment]
i've created a pull request to fix it:
https://github.com/RobinMalfait/Laravel-auto-form-generator/pull/18

**Comment by RobinMalfait** [comment]
Didn't even realise that this used Doctrine. Also I'm not maintaining the package anymore (You might noticed that from the commits).

**Comment by dwalker109** [comment]
Closing since, well, we've all moved on :+1:

**Comment by Jimbolino** [comment]
moved on to what?

**Comment by RobinMalfait** [comment]
I hope you are not using this dependency anymore 😅

**Comment by dwalker109** [comment]
Not since 2015, no - just noticed this was outstanding and I wanted closure! :D
